### ISSUE TITLE
Mods adding heads with command to User Collection

### ISSUE THREAD

**Issue by Flexo013** [Flexo013/HeadsWebsite#1]
Mods can currently already add heads using commands to the Main Collection. It would be nice if mods also could add heads in the same way to the User Collection.

**Comment by Fancypants** [comment]
If I'm not mistaken the heads you enter into the admin area will appear in both collections. Can't test it right now so correct me if I'm wrong.

**Comment by Fancypants** [comment]
Confirmed; heads get added to both databases like they should. Works as intended.

**Comment by Flexo013** [comment]
Can we upload with a command exclusively to the user database without it appearing in the Main Collection? Sometimes I have commands that I wish to add to the user database but not to the Main database.

**Comment by Fancypants** [comment]
Seems like a strange idea, can you explain to me what your workflow would be? Seems to me you like to either upload a head yourself by filling in your username in the admin area or by filling in a command you got from the User Collection. If you would like to add a head to the User collection you would just use the Home Generator. 

Maybe I don't understand the question, you want to manually create a command and want to use that command to enter a head?

**Comment by Flexo013** [comment]
Yeah, this was my old idea with fixing commands with wrong names. But now that we can rename this is no longer necessary.
