### ISSUE TITLE
Spelling error

### ISSUE THREAD

**Issue by Flexo013** [Flexo013/HeadsWebsite#10]
Page: http://heads.freshcoal.com/index.php

This sentence ![screenshot086](https://cloud.githubusercontent.com/assets/4507015/4928152/b936b492-6541-11e4-9cb2-017cb7d77dba.png) would be better as
`With this command you can create Playerhead Snapshots to decorate your Minecraft world with.`
or
`With these commands you can create Playerhead Snapshots to decorate your Minecraft world with.`

**Comment by Fancypants** [comment]
Fixed!

**Comment by Flexo013** [comment]
Just checked, still seem an issue on the page: http://heads.freshcoal.com/index.php
![screenshot087](https://cloud.githubusercontent.com/assets/4507015/4940632/2ffdf848-65dc-11e4-9792-b9d27deea105.png)

**Comment by Fancypants** [comment]
Strange, don't know how that happened, anyhow I fixed it again.

**Comment by Flexo013** [comment]
Somehow it got unfixed again.
![screenshot088](https://cloud.githubusercontent.com/assets/4507015/4950190/4f2e2d8e-6657-11e4-8777-3b1882e2e2ff.png)

**Comment by Flexo013** [comment]
Never mind, that is not the main page. That is the admin page.
http://heads.freshcoal.com/admin/index.php

**Comment by Fancypants** [comment]
Fixed, we'll probably be opening and closing this issue many more times in the future.
