### ISSUE TITLE
Website issues

### ISSUE THREAD

**Issue by Flexo013** [Flexo013/HeadsWebsite#11]
All heads in the user collection display as Steve heads:
![screenshot092](https://cloud.githubusercontent.com/assets/4507015/5001921/666db724-69fb-11e4-8769-ac57f58eed41.png)

Trying to add a new head to the user collection takes a lot of time and in the end the command does not work.

Main Collection is fine.

**Comment by Fancypants** [comment]
Not sure what is causing this, will look into it tonight.

**Comment by Fancypants** [comment]
This issue suddenly fixed itself which leads me to conclude the minecraft servers were involved in this temporary glitch. Will investigate when it happens again.
