### ISSUE TITLE
Heads are not added

### ISSUE THREAD

**Issue by Flexo013** [Flexo013/HeadsWebsite#12]
Users submitting a head will not have the new head added to the user collection. Even the admins are unable to add heads to the user or main collection.

The commands generate properly but the heads do not appear in the respective collections.

**Comment by Fancypants** [comment]
I am not able to replicate this bug, both versions work for me. Are you still having this issue?

**Comment by Flexo013** [comment]
Yes, heads do not seem to added for me:
![screenshot093](https://cloud.githubusercontent.com/assets/4507015/5015849/584d3d3a-6aa1-11e4-9f6e-07acec2883f2.png)
![screenshot094](https://cloud.githubusercontent.com/assets/4507015/5015848/5847e54c-6aa1-11e4-9964-cb335ef37855.png)
![screenshot095](https://cloud.githubusercontent.com/assets/4507015/5015847/5847c03a-6aa1-11e4-8c29-4f0916aae1d2.png)

**Comment by Flexo013** [comment]
Resolved, the issue was created my the ' character.

**Comment by Fancypants** [comment]
Yes I found out yesterday, Mark talked to you about it. This is still an security issue though, will look into it. As an added security measure the databases now daily backup (only when heads got added). I've improvement a few more other features, ill post an update about it one of these days.

**Comment by Flexo013** [comment]
Yeah, because I think we are currently not protected against [SQL injection](http://nl.wikipedia.org/wiki/SQL-injectie).
