### ISSUE TITLE
Performance issues Main Collection

### ISSUE THREAD

**Issue by Flexo013** [Flexo013/HeadsWebsite#13]
A friend of mine has reported that her laptop still has trouble handling the main collection. ("It crashes her Shockwave and browser.") As mentioned in #7, it would be nice if we could provide users with a light version of the main collection. 
#7: `There is no light collection for the main collection.`

**Comment by Fancypants** [comment]
I guess we could create a light version for the main collection, will look into it. I might even switch to an alternate version of copying since zeroclipboard gets heavy when hundreds of flash objects need to be loaded, even on more advanced computers with moderate connection.

**Comment by Fancypants** [comment]
Added: http://heads.freshcoal.com/maincollectionlist.php

**Comment by Flexo013** [comment]
You're a hero!
