### ISSUE TITLE
Old tags get removed when adding new tags

### ISSUE THREAD

**Issue by Flexo013** [Flexo013/HeadsWebsite#17]
It would be nice if the previous tags would be amended instead of replaced once a mod edits the tags.

Example:
A head has tag `fish`.
The tag `animal` is entered in the update field.

Currently: the tag `animal` replaces the tag `fish`.
Better: the head will have tags `fish` and `animal`.

**Comment by Fancypants** [comment]
I was already planning to do this, just didn't had the time to do so. Its working now! Maybe you also noticed you can delete tags with the little x next to the tags.

**Comment by Flexo013** [comment]
Yes I noticed :D
