### ISSUE TITLE
Contributors do not update after account name change

### ISSUE THREAD

**Issue by Flexo013** [Flexo013/HeadsWebsite#19]
_Small issue that does not have a high priority._

I changed the name of my secondary account from Veazo to Flexo.
Veazo is currently the top contributor on the website with 108 heads. I just tried uploading a head through the same account. Veazo is still at the top with 108 heads.

The contributors should be tracked by UUID and when displayed it should use their most recent display name. So for my example the site should say Flexo with 109 heads.

**Comment by Fancypants** [comment]
Contributors are now listed by UUID while showing their last used display name. As a added bonus the search function now searches for player UUID's too.
