### ISSUE TITLE
Remove and avoid duplicate heads

### ISSUE THREAD

**Issue by Flexo013** [Flexo013/HeadsWebsite#20]
Minecraft's skin storage already prevents duplicates. We could use this to prevent duplicates in our database. 

It would be nice to also perform this check on all previously uploaded heads.

Something to keep in mind is that the skins can be different according according to Mojang but the resulting heads might still be the same. So we might need to look into optimizing that.

**Comment by Fancypants** [comment]
Fixed!

Steve heads appear when the user is too fast with uploading heads after eachother. I still have to add a warning, now the Steve head shows with a command the player cannot use. I prevented the steves from uploading to the database so we don't have to delete the heads.

Also added a check for duplicates in the Heads and Deleted database so whenever we delete a head, bare in mind it cannot be uploaded again.
