### ISSUE TITLE
Admin page buttons do not show up when window width is below 1190 pixels

### ISSUE THREAD

**Issue by Flexo013** [Flexo013/HeadsWebsite#25]
Half screen:
![screenshot200](https://cloud.githubusercontent.com/assets/4507015/6896244/9b9b5388-d6e9-11e4-9ced-9c20b1ad481b.png)

Bigger screen (1190 pixels wide):
![screenshot201](https://cloud.githubusercontent.com/assets/4507015/6896245/9b9d0552-d6e9-11e4-967e-e734a08c614b.png)

**Comment by Fancypants** [comment]
I'm slowly turning the site into a more responsive design, forgot to replace the admin menu. It's fixed now.
