### ISSUE TITLE
Scroll issue on mod head deletion

### ISSUE THREAD

**Issue by Flexo013** [Flexo013/HeadsWebsite#3]
Upon deletion of a head the vertical location should be preserved once the page refreshes. This would make it easier for mods to delete multiple heads.

**To reproduce:**
Go here: http://heads.freshcoal.com/admin/del.php
Scroll down the page and delete a head.
After deletion the page refreshes.
You are now back on top of the page: http://heads.freshcoal.com/admin/del.php

**Comment by Fancypants** [comment]
Heads are sorted on their PID (last to first), when a head gets deleted I certainly can't point the page back to the PID we just deleted. So now the page looks for the PID just 1 above the PID you just deleted and brings you to the head next to the one you deleted. Hope this helps.

**Comment by Flexo013** [comment]
Awesome job!
