### ISSUE TITLE
Explain that Head names should be English

### ISSUE THREAD

**Issue by Flexo013** [Flexo013/HeadsWebsite#5]
On this page: http://heads.freshcoal.com/index.php

Above the second box we should add that we only want English head names, Potentially mention that non-English head names will be removed.

**Comment by Fancypants** [comment]
Added a sentence saying "please use English names", for the possible remove notice I should add some sort of a disclaimer somewhere saying we preserve the right to remove heads that don't match our standards I.E. wrong name, bad texture, insulting textures or wrong transparency. Not sure where to create said page though.

**Comment by Flexo013** [comment]
Maybe create a page called "Head Info". This page would not have to be added to the main top menu, but I would be linked from where is currently says "please use English names". We could change that to: "please use English names. More info **here**."
