### ISSUE TITLE
Allow Mods to rename heads in the database

### ISSUE THREAD

**Issue by Flexo013** [Flexo013/HeadsWebsite#6]
Somewhat an extension of #5.

When users do not enter a head name for a perfectly good head we have to remove it now and re-add it with the correct head name. It would be nice if mods could edit the name of an existing head in the database.

(This also allows for translation in cases where non-English names are entered by the users.)

**Comment by Flexo013** [comment]
This is probably easiest to implement by using a light version of user collection within the mods panel. This page already displays the names.

**Comment by Fancypants** [comment]
I don't like multiple pages to edit just one head so I adjusted the delete page to be able to rename heads. Just don't accidentally press the delete button (or a head) ;).

**Comment by Fancypants** [comment]
Forgot to change the name in the command too. If you renamed heads you have to do it again for it to have effect on the /give command, sorry.
