### ISSUE TITLE
Hitbox of buttons is not the right size

### ISSUE THREAD

**Issue by Flexo013** [Flexo013/HeadsWebsite#8]
The buttons on the site work fine. It would be a slight enhancement to fix the hitbox issue with the blue buttons.
Clicking here works fine:
![screenshot081](https://cloud.githubusercontent.com/assets/4507015/4913806/b02aafb8-64b8-11e4-9c00-1acb2bdc3b7c.png)
Clicking here does not work (even though the user is clicking on the blue button):
![screenshot082](https://cloud.githubusercontent.com/assets/4507015/4913807/b02e2cb0-64b8-11e4-9caa-76784cb54538.png)

**Comment by Fancypants** [comment]
Fixed, hitbox now consists of the entire button.
