### ISSUE TITLE
Spelling error

### ISSUE THREAD

**Issue by Flexo013** [Flexo013/HeadsWebsite#9]
There is a spelling error on the mod page: http://heads.freshcoal.com/admin/

![screenshot084](https://cloud.githubusercontent.com/assets/4507015/4927782/8bdeb83a-653e-11e4-8fe9-307e89943df5.png)
Should be:
`Or use an existing command:`

**Comment by Fancypants** [comment]
Seems like I've been spelling that wrong all my life. Fixed!
